fix tests

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -56,14 +56,14 @@ jobs:
 
       - name: Create DB And User
         run: |
-          docker exec mysql ls /docker-entrypoint-initdb.d/ \
-          docker exec mysql ls -l /docker-entrypoint-initdb.d/ \
-          docker exec mysql cat /docker-entrypoint-initdb.d/createdb.sql \
+          docker exec mysql ls /docker-entrypoint-initdb.d/
+          docker exec mysql ls -l /docker-entrypoint-initdb.d/
+          docker exec mysql cat /docker-entrypoint-initdb.d/createdb.sql
           if [ -f /docker-entrypoint-initdb.d/createdb.sql ]; then \
-            docker exec mysql mysql -u ${{ env.MYSQL_ROOT }} -p${{ env.MYSQL_ROOT_PASSWORD }} < /docker-entrypoint-initdb.d/createdb.sql \
+            docker exec mysql mysql -u ${{ env.MYSQL_ROOT }} -p${{ env.MYSQL_ROOT_PASSWORD }} < /docker-entrypoint-initdb.d/createdb.sql; \
           else \
-            echo "SQL file not found!" \
-            exit 1 \
+            echo "SQL file not found!"; \
+            exit 1; \
           fi
 
       - name: Install PHP
