fix tests

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -41,12 +41,6 @@ jobs:
             -v ${{ github.workspace }}/tests/Drivers/MySql/my.cnf:/etc/mysql/my.cnf \
             -v ${{ github.workspace }}/tests/Drivers/MySql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
             mysql:5.7
-
-      - name: List files in Docker container
-        run: docker exec mysql ls /docker-entrypoint-initdb.d/
-
-      - name: Check file permissions in Docker container
-        run: docker exec mysql ls -l /docker-entrypoint-initdb.d/
           
       - name: Wait for MySQL to be ready
         run: |
@@ -64,7 +58,13 @@ jobs:
         run: |
           docker exec mysql ls /docker-entrypoint-initdb.d/ \
           docker exec mysql ls -l /docker-entrypoint-initdb.d/ \
-          docker exec mysql mysql -u ${{ env.MYSQL_ROOT }} -p${{ env.MYSQL_ROOT_PASSWORD }} < /docker-entrypoint-initdb.d/createdb.sql
+          docker exec mysql cat /docker-entrypoint-initdb.d/createdb.sql \
+          if [ -f /docker-entrypoint-initdb.d/createdb.sql ]; then
+            docker exec mysql mysql -u ${{ env.MYSQL_ROOT }} -p${{ env.MYSQL_ROOT_PASSWORD }} < /docker-entrypoint-initdb.d/createdb.sql
+          else
+            echo "SQL file not found!"
+            exit 1
+          fi
 
       - name: Install PHP
         uses: shivammathur/setup-php@v2
